In [4]:
import numpy as np

In [3]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

## how to save

In [4]:
#np.save('save_as',name_of_array)
np.save('saved_arr',arr)

In [6]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## how to load saved arr

In [8]:
np.load('saved_arr.npy')

array([0, 1, 2, 3, 4, 5])

In [11]:
arr3=arr
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
arr2=np.load('saved_arr.npy')
arr2

array([0, 1, 2, 3, 4, 5])

## in order to save more than one array make a zip which can input more than one array

In [16]:
np.savez('zip.npz',a=arr2,b=arr3)

In [20]:
ans=np.load('zip.npz')


In [21]:
ans['a']

array([0, 1, 2, 3, 4, 5])

In [22]:
ans['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## save as txt files

In [7]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.savetxt('saved.txt',arr,delimiter=',')

In [11]:
arr1=np.loadtxt('saved.txt',delimiter=',')
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

## PANDAS - Series

In [38]:
import pandas as pd
from pandas import Series, DataFrame

In [40]:
an=Series([1,2,3,4,5])
an

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [43]:
an1=Series([2312,3425,2454,5235,32523],index=['jam','sam','tom','harry','jonh'])
an1

jam       2312
sam       3425
tom       2454
harry     5235
jonh     32523
dtype: int64

## convert series to dictionary or vice versa

In [48]:
an1_dict=an1.to_dict()
an1_dict

{'harry': 5235L, 'jam': 2312L, 'jonh': 32523L, 'sam': 3425L, 'tom': 2454L}

In [50]:
an1_series=Series(an1_dict)
an1_series

harry     5235
jam       2312
jonh     32523
sam       3425
tom       2454
dtype: int64

## converting dictionary to series with adding new indexing and removing uncommon indexs

In [51]:
name=['sam','jam','kam','fam']

In [53]:
an2=Series(an1_dict, index=name)
an2

sam    3425.0
jam    2312.0
kam       NaN
fam       NaN
dtype: float64

In [54]:
# isnull and notnull functions
pd.isnull(an2)

sam    False
jam    False
kam     True
fam     True
dtype: bool

In [55]:
pd.notnull(an2)

sam     True
jam     True
kam    False
fam    False
dtype: bool

In [56]:
an1_series

harry     5235
jam       2312
jonh     32523
sam       3425
tom       2454
dtype: int64

In [57]:
an2

sam    3425.0
jam    2312.0
kam       NaN
fam       NaN
dtype: float64

In [58]:
# common will add up and uncommaon will nan
an1_series + an2

fam         NaN
harry       NaN
jam      4624.0
jonh        NaN
kam         NaN
sam      6850.0
tom         NaN
dtype: float64

In [59]:
an2.name='Names'
an2

sam    3425.0
jam    2312.0
kam       NaN
fam       NaN
Name: Names, dtype: float64

In [62]:
an2.index.name='first_name'
an2

first_name
sam    3425.0
jam    2312.0
kam       NaN
fam       NaN
Name: Names, dtype: float64